config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'main#start', as: 'main_start'
  get '/game', to: 'game#index', as: 'game_index'
  get '/main/final', to: 'main#final', as: 'main_final'
  patch '/game/play_a_card', to: 'game#save_cards', as: 'game_play_a_card'
  post '/main/new_game', to: 'main#new_game', as: 'main_new_game'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bin_card.rb
# frozen_string_literal: true

class BinCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  validates :value, uniqueness: true
  has_one :user_card
  has_one :table_card
  has_one :bin_card
  has_one :temporary_card_place
  has_one :user, through: :user_card
  # has_one :user, through: :bin_card
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user
end

app/models/table_card.rb
# frozen_string_literal: true

class TableCard < ApplicationRecord
  belongs_to :card
end

app/models/temporary_card_place.rb
# frozen_string_literal: true

class TemporaryCardPlace < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :user_card
  has_one :bin_card
end

app/models/user_card.rb
# frozen_string_literal: true

class UserCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
# frozen_string_literal: true

class GameController < ApplicationController
  def index
    @user1 = User.where(which_user: "user1").first
    @user2 = User.where(which_user: "user2").first
    @active_user = Game.first.user.nick
    @cards_user1 = Card.where(users: { which_user: "user1" }).joins(:user, :user_card)
    @cards_user2 = Card.where(users: { which_user: "user2" }).joins(:user, :user_card)
    @cards_active_user = Card.where(user_cards: { user: Game.first.user }).joins(:user, :user_card)
    @cards_row0 = Card.where(table_cards: { row_id: 0 }).joins(:table_card).order(value: :asc)
    @cards_row1 = Card.where(table_cards: { row_id: 1 }).joins(:table_card).order(value: :asc)
    @cards_row2 = Card.where(table_cards: { row_id: 2 }).joins(:table_card).order(value: :asc)
    @cards_row3 = Card.where(table_cards: { row_id: 3 }).joins(:table_card).order(value: :asc)
    @cards_user1_bin =  BinCard.where(users: { which_user: "user1" }).joins(:user)
    @cards_user2_bin =  BinCard.where(users: { which_user: "user2" }).joins(:user)
    @end_of_the_game =  end_of_the_game?
  end

  def save_cards
    card = Card.find(card_params["card"].to_i)
    row = card_params["row"].to_i
    if (rows_to_take(card).include? row) || (row_to_add_in(card) == row)
      if Game.first.user == User.where(which_user: "user1").first
        TemporaryCardPlace.create(card: card, row: row, user: active_user)
        change_active_user
      else
        TemporaryCardPlace.create(card: card, row: row, user: active_user)
        change_active_user
        TemporaryCardPlace.joins(:card).order("cards.value").each do |temp|
          play_a_card(temp.card, temp.row, temp.user)
        end
        TemporaryCardPlace.delete_all
      end
      redirect_to action: "index"
    else
      flash[:warning] = "You can't put card on that row"
      redirect_to action: "index"
    end
  end

  def play_a_card(card, row, user)
    if rows_to_take(card).include? row
      move_to_bin(row, user)
      TableCard.create(card: card, row_id: row)
      UserCard.where(card: card).first.delete
      change_active_user
    elsif row_to_add_in(card) == row
      if TableCard.where(row_id: row).count == 5
        move_to_bin(row, user)
      end
      UserCard.where(card: card).first.delete
      TableCard.create(card: card, row_id: row)
      change_active_user
    else
      if TableCard.where(row_id: row).count == 5
        move_to_bin(row, user)
      end
      UserCard.where(card: card).first.delete
      TableCard.create(card: card, row_id: row)
      change_active_user
    end
  end

  def move_to_bin(row, user)
    TableCard.where(row_id: row).each do |table_card|
      card = table_card.card
      BinCard.create(card: card, user: user)
      table_card.delete
    end
  end

  def last_card_in_row
    last_card_in_row = {}
    last_card_in_row[0] = Card.where(table_cards: { row_id: 0 }).joins(:table_card).order(value: :asc).last
    last_card_in_row[1] = Card.where(table_cards: { row_id: 1 }).joins(:table_card).order(value: :asc).last
    last_card_in_row[2] = Card.where(table_cards: { row_id: 2 }).joins(:table_card).order(value: :asc).last
    last_card_in_row[3] = Card.where(table_cards: { row_id: 3 }).joins(:table_card).order(value: :asc).last
    last_card_in_row
  end

  def rows_to_take(card)
    rows = []
    (0...4).each do |r|
      if card.value < last_card_in_row[r].value
        rows.append(r)
      end
    end
    rows
  end

  def row_to_add_in(card)
    row_to_add_in = [0, 1, 2, 3] - rows_to_take(card)

    diff = {}
    row_to_add_in.each do |row|
      diff[row] = card.value - last_card_in_row[row].value
    end
    diff.min_by { |_k, v| v }.first
  end

  def card_params
    params.require(:card)
  end

  def change_active_user
    if active_user == User.first
      Game.first.update(user: User.last)
    else
      Game.first.update(user: User.first)
    end
  end

  def end_of_the_game?
    UserCard.first.nil?
  end

  def active_user
    Game.first.user
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def start; end

  def final
    @user1 = User.where(which_user: "user1").first
    @user2 = User.where(which_user: "user2").first
    @user1_negative_points = BinCard.where(users: { which_user: "user1" }).joins(:user, :card).sum(:negative_points)
    @user2_negative_points = BinCard.where(users: { which_user: "user2" }).joins(:user, :card).sum(:negative_points)
    @winner = if @user1_negative_points < @user2_negative_points
                @user1
              elsif @user1_negative_points > @user2_negative_points
                @user2
              else
                "remis"
              end
  end

  def new_game
    TableCard.destroy_all
    UserCard.destroy_all
    BinCard.destroy_all
    Card.destroy_all
    User.destroy_all
    Game.destroy_all
    user1 = User.create(which_user: "user1", nick: users_params["user1_nick"])
    user2 = User.create(which_user: "user2", nick: users_params["user2_nick"])
    Game.create(
      user: user1,
    )

    (1..24).each do |x|
      if x % 10 == 0
        Card.create(
          value: x,
          negative_points: 3
        )
      elsif x % 5 == 0 && x % 10 != 0
        Card.create(value: x,
                    negative_points: 2)
      elsif x % 11 == 0
        Card.create(value: x,
                    negative_points: 5)
      else
        Card.create(value: x,
                    negative_points: 1)
      end
    end

    cards = Card.all.sample(24)
    (0..3).each do |x|
      TableCard.create(card: cards[x], row_id: x)
    end
    (4..13).each do |x|
      UserCard.create(card: cards[x], user: user1)
    end
    (14..23).each do |x|
      UserCard.create(card: cards[x], user: user2)
    end

    redirect_to :game_index
  end

  def users_params
    params.require(:user)
  end
  end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/game/_form.html.erb
<%= form_for(card, url: game_play_a_card_path) do |f| %>
  <%= f.hidden_field(:card, :value => card.id, ) %>
  <%= f.hidden_field(:row, :value => row) %>
  <%= f.submit(row + 1) %>
<% end %> 

app/views/game/index.html.erb
<h3>Active user: <span class="active-user-nick"><%=@active_user%></span></h3>

<div class="game-flow">

    <div class="active-user-cards">
        <div class="overlay">It's <%=@active_user%>'s turn <button class="continue-btn">Continue</button></div>
        <%@cards_active_user.each do |card|%>
            <div class="card">
                <div class="card-value"><%=card.value%></div>
                <div class="card-negative-points"><%=card.negative_points%></div>
                <div class="card-buttons">
                    <%= render partial: 'form', locals: { card: card, row: 0} %>
                    <%= render partial: 'form', locals: { card: card, row: 1} %>
                    <%= render partial: 'form', locals: { card: card, row: 2} %>
                    <%= render partial: 'form', locals: { card: card, row: 3} %>
                </div>
            </div>
        <%end%>
    </div>

    <div class="game-table">
        <h3>Table</h3>

        <div class="card-rows">
            <div class="table-cards-row">
                <h2>1</h2>
                <%@cards_row0.each do |card|%>
                    <div class="card">
                        <div class="card-value"><%=card.value%></div>
                        <div class="card-negative-points"><%=card.negative_points%></div>
                    </div>
                <%end%>
            </div>
            <div class="table-cards-row">
                <h2>2</h2>
                <%@cards_row1.each do |card|%>
                    <div class="card">
                        <div class="card-value"><%=card.value%></div>
                        <div class="card-negative-points"><%=card.negative_points%></div>
                    </div>
                <%end%>
            </div>
            <div class="table-cards-row">
                <h2>3</h2>
                <%@cards_row2.each do |card|%>
                    <div class="card">
                        <div class="card-value"><%=card.value%></div>
                        <div class="card-negative-points"><%=card.negative_points%></div>
                    </div>
                <%end%>
            </div>
            <div class="table-cards-row">
                <h2>4</h2>
                <%@cards_row3.each do |card|%>
                    <div class="card">
                        <div class="card-value"><%=card.value%></div>
                        <div class="card-negative-points"><%=card.negative_points%></div>
                    </div>
                <%end%>
            </div>
        </div>
        <!--
        <div class="bins">
            <div class="user-bin">
                <h3><%=@user1.nick%>'s Bin</h3>
                <div class="user-bin-cards">
                    <%@cards_user1_bin.each do |bin_card|%>
                        <div class="card">
                            <div class="card-value"><%=bin_card.card.value%></div>
                            <div class="card-negative-points"><%=bin_card.card.negative_points%></div>
                        </div>
                    <%end%>
                </div>
            </div>

            <div class="user-bin">
                <h3><%=@user2.nick%>'s Bin</h3>
                <div class="user-bin-cards">
                    <%@cards_user2_bin.each do |bin_card|%>
                        <div class="card">
                            <div class="card-value"><%=bin_card.card.value%></div>
                            <div class="card-negative-points"><%=bin_card.card.negative_points%></div>
                        </div>
                    <%end%>
                </div>
            </div>
        </div>
        -->
    <% if @end_of_the_game %>
        <%= link_to "See results", main_final_path, :class => "results-button"%>
    <% end %>
    </div>

</div>

<style>

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SzescBierze</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/final.html.erb
<div class="form-wrap final">
    <% if @winner == "remis" %>
        <h1><%=@winner%></h1>
    <% else %>
        <h1>The winner is: <%=@winner.nick%></h1>
    <% end %>

    <h3><%=@user1.nick%> negative points: <%=@user1_negative_points%></h3>
    <h3><%=@user2.nick%> negative points: <%=@user2_negative_points%></h3>
</div>
<%= link_to "New game", main_start_path, :class => "results-button"%>

app/views/main/start.html.erb
<div class="form-wrap">
  <%= form_for(:user, url: main_new_game_path) do |f| %>
    <h3>Let's start</h3>
    <div class="input-wrap">
        <%= f.label "1st User nickname" %>
        <%= f.text_field :user1_nick, placeholder: "Enter nickname"%>
    </div>
    <div class="input-wrap">
        <%= f.label "2nd User nickname"%>
        <%= f.text_field :user2_nick, placeholder: "Enter nickname" %>
    </div>
    <%= f.submit("Let's play!") %>
  <% end %>
</div>

<style>


</style>